# raw data path
raw_data_path: data/raw/churn.csv

train_path: data/train/train.csv

test_path: data/test/test.csv

val_path: data/validation/val.csv

numerical_columns: ['credit_score','age','tenure','balance','products_number','credit_card','active_member','estimated_salary']

categorical_columns: ['country','gender']

target_column: 'churn'

preprocessor_obj: 'model/preprocessor.pkl'

processed_X_path_csv: 'data/processed/X_processed.csv'

processed_y_path_csv: 'data/processed/y.csv'

trained_model_path: 'artifacts/models/random_forest_model.pkl'

columns_to_drop: customer_id

best_model:
  name: RandomForestClassifier
  hyperparameters:
    n_estimators: 100
    random_state: 42

best_run_id: eb9f231e274b43288d3cb42eb22c69b7

all_columns: ['country_France', 'country_Germany', 'country_Spain', 'gender_Female', 'gender_Male', 'credit_score', 'age', 'tenure', 'balance', 'products_number', 'credit_card', 'active_member', 'estimated_salary']


