# raw data path
raw_data_path: data/raw/churn.csv

train_path: data/train/train.csv

test_path: data/test/test.csv

val_path: data/validation/val.csv

numerical_columns: ['credit_score','age','tenure','balance','products_number','credit_card','active_member','estimated_salary']

categorical_columns: ['country','gender']

target_column: 'churn'

preprocessor_obj: 'model/preprocessor.pkl'

processed_X_path_csv: 'data/processed/X_processed.csv'

processed_y_path_csv: 'data/processed/y.csv'

trained_model_path: 'artifacts/models/random_forest_model.pkl'

columns_to_drop: customer_id

best_model:
  name: LGBMClassifier
  hyperparameters:
    n_estimators: 100
    random_state: 42
    verbosity: -1

logged_model: 'runs:/d3fa1277ff7e4af5b2aeae091a444551/model'

all_columns: ['credit_score', 'country', 'gender', 'age', 'tenure', 'balance','products_number', 'credit_card', 'active_member', 'estimated_salary']


